# Generated by Django 5.1.3 on 2024-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeda_fiat', models.CharField(max_length=10)),
                ('moeda_cripto', models.CharField(max_length=10)),
                ('cotacao', models.DecimalField(decimal_places=8, max_digits=18)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('validade', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Cotação',
                'verbose_name_plural': 'Cotações',
                'unique_together': {('moeda_fiat', 'moeda_cripto', 'validade')},
            },
        ),
    ]
