# Generated by Django 5.1.3 on 2024-11-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SatoshiTodayApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('date_price', models.DateTimeField(auto_now_add=True)),
                ('moeda_fiat', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-date_price'],
                'unique_together': {('date_price', 'moeda_fiat')},
            },
        ),
    ]
